### ISSUE TITLE
Image Viewer

### ISSUE THREAD

**Issue by Pamel-a** [madskristensen/OutputWindowFilter#3]
Hello mads, i see on market place that you have many `Visual Studio` extension, i'm following this feature request on `Visual Studio` forum:

https://developercommunity.visualstudio.com/t/An-option-to-preview-images-when-they-ar/10419941

It got many upvotes but Microsoft didn't cared about it, i wonder if you could take a look at it, maybe you have something like?

**Comment by madskristensen** [comment]
Hi @Pamel-a 

This is a weird coincidence. I'm working on that right now!! 

See this screenshot where I hover over `icon2.png` and it shows me the image based on the relative file path

![image](https://github.com/madskristensen/OutputWindowFilter/assets/1258877/20e35e9f-49ae-4305-aa19-6738bb63eee3)

**Comment by Pamel-a** [comment]
Wow cool! Do you think is possible to zoom in/ out the image when you scroll the thumbnail? this would be useful for small images.
I'm working with OpenCV images and sometimes there are some small images that are easier to note some kind of detail after enlarging it.

**Comment by Pamel-a** [comment]
An example from the [Image Watch](https://marketplace.visualstudio.com/items?itemName=VisualCPPTeam.ImageWatchForVisualStudio2022) extension:

![devenv_jpBuqlVxe3](https://github.com/madskristensen/OutputWindowFilter/assets/142637979/3ae84321-83c3-4775-ad0e-8c6233fc07b2)
